/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.riten.gradle;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class AddServlet extends HttpServlet
{
  //public void service(HttpServletRequest req, HttpServletResponse res) throws IOException
  public void doPost(HttpServletRequest req, HttpServletResponse res) throws IOException
  
  {
	  int i = Integer.parseInt(req.getParameter("num1"));
	  int j = Integer.parseInt(req.getParameter("num2"));
	  int k = i+j;
	  PrintWriter out = res.getWriter();
	  //System.out.println("result is " + k);
	  out.println("result is " + k);
	  
  }
}
